### ISSUE TITLE
请问能作为群组的关键词搜索吗

### ISSUE THREAD

**Issue by despacito008** [chuangzhu/telegram-find-in-channel-bot#2]
有相关的api吗 非管理员能查询关键词吗

**Comment by chuangzhu** [comment]
非管理员的搜索的功能我有考虑添加，我想做成当管理员设置为允许其他人搜索时，可通过管理员发送的链接进入机器人的模式。

用于群组的搜索暂时不考虑添加。

**Comment by despacito008** [comment]
还有一个是公开性搜索，即为频道开放，所有人搜索关键词都可以搜索到频道的内容

**Comment by despacito008** [comment]
> 非管理员的搜索的功能我有考虑添加，我想做成当管理员设置为允许其他人搜索时，可通过管理员发送的链接进入机器人的模式。
> 
> 用于群组的搜索暂时不考虑添加。

频道人数超过200人之后不能手动添加成员，怎样才能让机器人进入频道呢

**Comment by chuangzhu** [comment]
> 频道人数超过200人之后不能手动添加成员，怎样才能让机器人进入频道呢

应该也是可以添加管理员的。添加管理员的具体方法是在频道的编辑界面找到 Administrators，点击 Add Admin，然后搜索 FindInChannelBot。

**Comment by chuangzhu** [comment]
Added in 696b6f93a92ee764a9d207974e52af620fa1cf35
